// FRONT/ANGULAR/angularcrudseries/src/app/components/createpersonaje/createpersonaje.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Personaje } from 'src/app/models/Personaje';
import { Serie } from 'src/app/models/Serie';
import { ServiceSeries } from 'src/app/services/service.series';
import { Router } from '@angular/router';

@Component({
  selector: 'app-createpersonaje',
  templateUrl: './createpersonaje.component.html',
  styleUrls: ['./createpersonaje.component.css'],
})
export class CreatepersonajeComponent implements OnInit {
  public series!: Serie[];

  @ViewChild('controlnombre') controlNombre: ElementRef = new ElementRef('');
  @ViewChild('controlimagen') controlImagen: ElementRef = new ElementRef('');
  @ViewChild('selectserie') selectSerie!: ElementRef;

  constructor(private _service: ServiceSeries, private _router: Router) {}

  ngOnInit(): void {
    this._service.getSeries().subscribe((response) => {
      this.series = response;
      this.selectSerie.nativeElement.value = this.series[0].idSerie;
    });
  }

  createPersonaje(): void {
    let personaje: Personaje = new Personaje(
      0,
      this.controlNombre.nativeElement.value,
      this.controlImagen.nativeElement.value,
      parseInt(this.selectSerie.nativeElement.value)
    );
    this._service.createPersonaje(personaje).subscribe((response) => {
      this._router.navigate([
        '/personajes',
        this.selectSerie.nativeElement.value,
      ]);
    });
  }
}

<div *ngIf="series">
  <h1>Crear personaje</h1>
  <hr class="border border-danger opacity-100" />
  <form #createform="ngForm" (ngSubmit)="createPersonaje()">
    <div class="mt-3">
      <label class="form-label">Nombre</label>
      <input
        type="text"
        class="form-control"
        name="controlnombre"
        #controlnombre
      />
    </div>
    <div class="mt-3">
      <label class="form-label">Imagen</label>
      <input
        type="text"
        class="form-control"
        name="controlimagen"
        #controlimagen
      />
    </div>
    <div class="mt-3">
      <label class="form-label">Serie</label>
      <select class="form-select" name="selectserie" #selectserie>
        <option *ngFor="let serie of series" [value]="serie.idSerie">
          {{ serie.nombre }}
        </option>
      </select>
    </div>
    <button class="btn btn-primary w-100 mt-3">Crear personaje</button>
  </form>
</div>

// FRONT/VUE/vuecrudseries/src/components/CreatePersonaje.vue
<template>
  <div>
    <h1>Crear personaje</h1>
    <hr class="border border-primary opacity-100" />
    <form
      @submit.prevent="createPersonaje()"
      class="w-75 mx-auto"
      v-if="series.length > 0"
    >
      <div class="mt-3">
        <label class="form-label">Nombre</label>
        <input type="text" class="form-control" v-model="personaje.nombre" />
      </div>
      <div class="mt-3">
        <label class="form-label">Imagen</label>
        <input type="text" class="form-control" v-model="personaje.imagen" />
      </div>
      <div class="mt-3">
        <label class="form-label">Serie</label>
        <select class="form-select" v-model="personaje.idSerie">
          <option v-for="serie in series" :key="serie" :value="serie.idSerie">
            {{ serie.nombre }}
          </option>
        </select>
      </div>
      <button class="btn btn-primary w-100 mt-3">Crear personaje</button>
    </form>
    <img v-else src="../assets/images/loading.gif" />
  </div>
</template>

<script>
import ServiceSeries from "@/services/ServiceSeries";
const service = new ServiceSeries();

export default {
  name: "CreatePersonaje",
  data() {
    return {
      personaje: {
        idPersonaje: 0,
        nombre: "",
        imagen: "",
        idSerie: 0,
      },
      series: [],
    };
  },
  methods: {
    createPersonaje() {
      service.createPersonaje(this.personaje).then((result) => {
        console.log(result);
        this.$router.push("/personajes/" + this.personaje.idSerie);
      });
    },
  },
  mounted() {
    service.getSeries().then((result) => {
      this.series = result;
    });
  },
};
</script>
