// FRONT/ANGULAR/angularcrudseries/src/app/components/personajesserie/personajesserie.component.ts
import { Component, OnInit } from '@angular/core';
import { ServiceSeries } from 'src/app/services/service.series';
import { ActivatedRoute, Params } from '@angular/router';
import { Personaje } from 'src/app/models/Personaje';

@Component({
  selector: 'app-personajesserie',
  templateUrl: './personajesserie.component.html',
  styleUrls: ['./personajesserie.component.css'],
})
export class PersonajesserieComponent implements OnInit {
  public idSerie!: number;
  public personajes?: Personaje[];

  constructor(
    private _service: ServiceSeries,
    private _activeRoute: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this._activeRoute.params.subscribe((params: Params) => {
      if (params['id']) {
        this.idSerie = params['id'];
        this.personajes = undefined; // para que salga loading
        this._service.getPersonajesSerie(this.idSerie).subscribe((response) => {
          this.personajes = response;
        });
      }
    });
  }
}

<div *ngIf="personajes">
  <h1>Personajes de {{ this.idSerie }}</h1>
  <hr class="border border-danger opacity-100" />
  <a class="btn btn-danger w-100 mb-3" [routerLink]="['/serie', this.idSerie]"
    >Volver a serie</a
  >
  <table class="table">
    <thead class="border-danger">
      <tr>
        <th>Nombre</th>
        <th>Imagen</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let person of personajes">
        <td>{{ person.nombre }}</td>
        <td>
          <img [src]="person.imagen" width="200" />
        </td>
      </tr>
    </tbody>
  </table>
</div>
<img
  *ngIf="!personajes"
  class="mx-auto d-block"
  src="../../../assets/images/loading.gif"
/>

// FRONT/VUE/vuecrudseries/src/components/PersonajesSerie.vue
<template>
  <div>
    <h1>Personajes Serie {{ this.$route.params.id }}</h1>
    <hr class="border border-primary opacity-100" />
    <div v-if="personajes.length > 0">
      <router-link
        class="btn btn-danger w-100"
        :to="'/serie/' + this.$route.params.id"
      >
        Volver
      </router-link>
      <table class="table mt-3">
        <thead class="border-primary">
          <tr>
            <th>Personaje</th>
            <th>Imagen</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="person in personajes" :key="person">
            <td>{{ person.nombre }}</td>
            <td>
              <img :src="person.imagen" width="150" height="200" />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <img v-else src="../assets/images/loading.gif" />
  </div>
</template>

<script>
import ServiceSeries from "@/services/ServiceSeries";
const service = new ServiceSeries();

export default {
  name: "PersonajesSerie",
  watch: {
    "$route.params.id"(nextVal, oldVal) {
      if (nextVal != oldVal) this.loadPersonajesSerie();
    },
  },
  data() {
    return {
      personajes: [],
    };
  },
  methods: {
    loadPersonajesSerie() {
      this.personajes = [];
      let serie = this.$route.params.id;
      service.loadPersonajesSerie(serie).then((result) => {
        this.personajes = result;
      });
    },
  },
  mounted() {
    this.loadPersonajesSerie();
  },
};
</script>
