// FRONT/ANGULAR/angularcrudseries/src/app/components/serie/serie.component.ts
import { Component, OnInit } from '@angular/core';
import { Serie } from 'src/app/models/Serie';
import { ServiceSeries } from 'src/app/services/service.series';
import { ActivatedRoute, Params } from '@angular/router';

@Component({
  selector: 'app-serie',
  templateUrl: './serie.component.html',
  styleUrls: ['./serie.component.css'],
})
export class SerieComponent implements OnInit {
  public serie?: Serie;

  constructor(
    private _service: ServiceSeries,
    private _activeRoute: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this._activeRoute.params.subscribe((params: Params) => {
      if (params['id']) {
        this.serie = undefined; // para que salga loading
        this._service.getSerie(params['id']).subscribe((response) => {
          this.serie = response;
        });
      }
    });
  }
}

<div *ngIf="serie" class="card d-block mx-auto w-75">
  <img class="card-img-top" [src]="serie.imagen" />
  <div class="card-body">
    <h5 class="card-title">{{ serie.nombre }}</h5>
    <p class="card-text">IMDB: {{ serie.puntuacion }}</p>
    <a
      class="btn btn-success w-100"
      [routerLink]="['/personajes', serie.idSerie]"
    >
      Personajes
    </a>
  </div>
</div>
<img
  *ngIf="!serie"
  class="d-block mx-auto"
  src="../../../assets/images/loading.gif"
/>

// FRONT/VUE/vuecrudseries/src/components/SerieComponent.vue
<template>
  <div class="w-75 mx-auto">
    <div class="card" v-if="serie">
      <img class="card-img-top" :src="serie.imagen" />
      <div class="card-body">
        <h5 class="card-title fw-bold">{{ serie.nombre }}</h5>
        <p class="card-text">Puntuación IMDB: {{ serie.puntuacion }}</p>
        <router-link
          class="btn btn-success w-100"
          :to="'/personajes/' + serie.idSerie"
        >
          Personajes
        </router-link>
      </div>
    </div>
    <img v-else src="../assets/images/loading.gif" />
  </div>
</template>

<script>
import ServiceSeries from "@/services/ServiceSeries";
const service = new ServiceSeries();

export default {
  name: "SerieComponent",
  watch: {
    "$route.params.id"(nextVal, oldVal) {
      if (nextVal != oldVal) this.searchSerie();
    },
  },
  data() {
    return {
      serie: null,
    };
  },
  methods: {
    searchSerie() {
      this.serie = null;
      let serie = this.$route.params.id;
      service.searchSerie(serie).then((result) => {
        this.serie = result;
      });
    },
  },
  mounted() {
    this.searchSerie();
  },
};
</script>
