// FRONT/ANGULAR/angularcrudseries/src/app/components/updatepersonaje/updatepersonaje.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Personaje } from 'src/app/models/Personaje';
import { Serie } from 'src/app/models/Serie';
import { ServiceSeries } from 'src/app/services/service.series';
import { Router } from '@angular/router';

@Component({
  selector: 'app-updatepersonaje',
  templateUrl: './updatepersonaje.component.html',
  styleUrls: ['./updatepersonaje.component.css'],
})
export class UpdatepersonajeComponent implements OnInit {
  public series!: Serie[];
  public personajes!: Personaje[];
  public serie!: Serie;
  public personaje!: Personaje;

  @ViewChild('selectserie') selectSerie!: ElementRef;
  @ViewChild('selectpersonaje') selectPersonaje!: ElementRef;

  constructor(private _service: ServiceSeries, private _router: Router) {}

  ngOnInit(): void {
    this._service.getSeries().subscribe((response) => {
      this.series = response;
    });
    this._service.getPersonajes().subscribe((response) => {
      this.personajes = response;
    });
  }

  modificarPersonaje(): void {
    let serie = parseInt(this.selectSerie.nativeElement.value);
    let personaje = parseInt(this.selectPersonaje.nativeElement.value);
    this._service.updatePersonaje(serie, personaje).subscribe((response) => {
      this._router.navigate(['/personajes', serie]);
    });
  }

  dataSerie(): void {
    let serie = parseInt(this.selectSerie.nativeElement.value);
    this._service.getSerie(serie).subscribe((response) => {
      this.serie = response;
    });
  }

  dataPersonaje(): void {
    let personaje = parseInt(this.selectPersonaje.nativeElement.value);
    this._service.getPersonaje(personaje).subscribe((response) => {
      this.personaje = response;
    });
  }
}

<div *ngIf="series && personajes">
  <h1>Modificar personajes</h1>
  <hr class="border border-danger opacity-100" />
  <form #updateform="ngForm" (ngSubmit)="modificarPersonaje()">
    <div class="mt-3">
      <label class="form-label">Serie</label>
      <select
        class="form-select"
        name="selectserie"
        #selectserie
        (change)="dataSerie()"
      >
        <option *ngFor="let serie of series" [value]="serie.idSerie">
          {{ serie.nombre }}
        </option>
      </select>
    </div>
    <div class="mt-3">
      <label class="form-label">Personaje</label>
      <select
        class="form-select"
        name="selectpersonaje"
        #selectpersonaje
        (change)="dataPersonaje()"
      >
        <option *ngFor="let person of personajes" [value]="person.idPersonaje">
          {{ person.nombre }}
        </option>
      </select>
    </div>
    <button class="btn btn-primary w-100 mt-3">Modificar personaje</button>
  </form>
</div>
<div class="mt-3 row" *ngIf="serie || personaje">
  <hr class="border border-danger opacity-100" />
  <div class="col-6" *ngIf="serie">
    <h2>{{ serie.nombre }}</h2>
    <img [src]="serie.imagen" class="img-fluid w-100" style="height: 450px" />
  </div>
  <div class="col-6" *ngIf="personaje">
    <h2>{{ personaje.nombre }}</h2>
    <img
      [src]="personaje.imagen"
      class="img-fluid w-100"
      style="height: 450px"
    />
  </div>
</div>
<img
  *ngIf="!series || !personajes"
  class="mx-auto d-block"
  src="../../../assets/images/loading.gif"
/>

// FRONT/VUE/vuecrudseries/src/components/UpdatePersonaje.vue
<template>
  <div>
    <h1>Modificar personaje</h1>
    <hr class="border border-primary opacity-100" />
    <form
      @submit.prevent="updatePersonaje()"
      v-if="personajes.length > 0 && series.length > 0"
      class="w-75 mx-auto"
    >
      <div class="mt-3">
        <label class="form-label">Serie</label>
        <select class="form-select" v-model="serie" @change="loadSerie()">
          <option v-for="serie in series" :key="serie" :value="serie.idSerie">
            {{ serie.nombre }}
          </option>
        </select>
      </div>
      <div class="mt-3">
        <label class="form-label">Personaje</label>
        <select
          class="form-select"
          v-model="personaje"
          @change="loadPersonaje()"
        >
          <option
            v-for="person in personajes"
            :key="person"
            :value="person.idPersonaje"
          >
            {{ person.nombre }}
          </option>
        </select>
      </div>
      <button class="btn btn-primary mt-3 w-100">Modificar personaje</button>
    </form>
    <img v-else src="../assets/images/loading.gif" />
    <div class="row mt-3 container-fluid" v-if="datosSerie || datosPersonaje">
      <hr class="border border-primary opacity-100" />
      <div class="col-6" v-if="datosSerie">
        <h2>{{ datosSerie.nombre }}</h2>
        <img :src="datosSerie.imagen" class="w-100" />
      </div>
      <div class="col-6" v-if="datosPersonaje">
        <h2>{{ datosPersonaje.nombre }}</h2>
        <img :src="datosPersonaje.imagen" class="w-100" />
      </div>
    </div>
  </div>
</template>

<script>
import ServiceSeries from "@/services/ServiceSeries";
const service = new ServiceSeries();

export default {
  name: "UpdatePersonaje",
  data() {
    return {
      series: [],
      personajes: [],
      serie: null,
      personaje: null,
      datosSerie: null,
      datosPersonaje: null,
    };
  },
  methods: {
    updatePersonaje() {
      service.updatePersonaje(this.personaje, this.serie).then((result) => {
        console.log(result);
        this.$router.push("/personajes/" + this.serie);
      });
    },
    loadSerie() {
      service.searchSerie(this.serie).then((result) => {
        this.datosSerie = result;
      });
    },
    loadPersonaje() {
      service.searchPersonaje(this.personaje).then((result) => {
        this.datosPersonaje = result;
      });
    },
  },
  mounted() {
    service.getSeries().then((result) => {
      this.series = result;
    });
    service.getPersonajes().then((result) => {
      this.personajes = result;
    });
  },
};
</script>
