// FRONT/REACT/reactclases/src/components/Comic.js
import { Component } from "react";

class Comic extends Component {
    render() {
        return (
            <div>
                <h2 style={{ color: "red" }}>{this.props.comic.titulo}</h2>
                <h3>{this.props.comic.descripcion}</h3>
                <img src={this.props.comic.imagen}
                    style={{ width: "150px", height: "150px" }} alt="" /><br />
                <button onClick={() => {
                    this.props.selectFav(this.props.comic)
                }}>Seleccionar favorito</button>
                <button onClick={() => {
                    this.props.eliminarComic(this.props.index);
                }}>Eliminar comic</button>
            </div>
        );
    }
}

export default Comic;

// FRONT/VUE/vuecomunicacioncomponents/src/components/ComicComponent.vue
<template>
    <div>
        <h2>{{ comic.titulo }}</h2>
        <h3>{{ comic.descripcion }}</h3>
        <h4 :class="{
            rojo: comic.year <= 2000,
            verde: comic.year > 2000
        }">
            Año: {{ comic.year }}
        </h4>
        <img :src="comic.imagen" /> <br />
        <button @click="seleccionarFav()">Marcar como favorito</button>
        <button @click="eliminarComic()" style="background-color:red;color:white">Eliminar</button>
    </div>
</template>

<script>
export default {
    name: "ComicComponent",
    props: ["comic", "index"],
    methods: {
        seleccionarFav() {
            this.$emit("seleccionarFav", this.comic);
        },
        eliminarComic() {
            this.$emit("eliminarComic", this.index);
        }
    }
}
</script>

<style>
@import "../assets//css/estilocomics.css";
</style>
