// FRONT/REACT/reactrutasforms/src/components/SeleccionMultiple.js
import React, { Component } from 'react'

export default class SeleccionMultiple extends Component {
    selectMultiple = React.createRef();

    generarOptions = () => {
        let options = [];
        for (let i = 0; i <= 10; i++)
            options.push(<option key={i} value={"Elemento " + i}>{"Elemento " + i}</option>);
        return options;
    }

    state = {
        seleccionados: ""
    }

    mostrarSeleccionados = (event) => {
        event.preventDefault();
        let options = this.selectMultiple.current.options;
        let datos = "";
        for (let option of options) // (let option in options) recorre cada índice
            if (option.selected) datos += option.value + ", ";
        this.setState({
            seleccionados: datos
        });
    }

    render() {
        return (
            <div>
                <h1>Selección múltiple</h1>
                <form onSubmit={this.mostrarSeleccionados}>
                    <label>Selecciona elementos</label>
                    <select ref={this.selectMultiple} size="10" multiple>
                        {this.generarOptions()}
                    </select>
                    <button>Mostrar selección</button>
                </form>
                <h1 style={{ color: "green" }}>{this.state.seleccionados}</h1>
            </div>
        );
    }
}

// FRONT/VUE/vuecomunicacioncomponents/src/components/SeleccionMultiple.vue
<template>
    <div>
        <h1>Selección multiple</h1>
        <form @submit.prevent="mostrarSeleccionados()">
            <select v-model="selectMultiple" multiple :size="comics.length">
                <option :value="comic" v-for="comic in comics" :key="comic">
                    {{ comic }}
                </option>
            </select>
            <button>Mostrar seleccionados</button>
        </form>
        <h3>{{ seleccionados }}</h3>
        <!--
        <div v-if="selectMultiple.length > 0">
            <div v-for="selected in selectMultiple" :key="selected">
                <h2>{{ selected }}</h2>
            </div>
        </div>
        -->
    </div>
</template>

<script>
export default {
    name: "SeleccionMultiple",
    data() {
        return {
            selectMultiple: [],
            seleccionados: "",
            comics: ["Spiderman", "Wolverine", "Avengers", "Batman"]
        }
    },
    methods: {
        mostrarSeleccionados() {
            this.seleccionados = "";
            for (let selected of this.selectMultiple)
                this.seleccionados += selected + ", "
        }
    }
}
</script>
