// FRONT/VUE/vuecomunicacioncomponents/src/components/ComicComponent.vue
<template>
    <div>
        <h2>{{ comic.titulo }}</h2>
        <h3>{{ comic.descripcion }}</h3>
        <h4 :class="{
            rojo: comic.year <= 2000,
            verde: comic.year > 2000
        }">
            Año: {{ comic.year }}
        </h4>
        <img :src="comic.imagen" /> <br />
        <button @click="seleccionarFav()">Marcar como favorito</button>
        <button @click="eliminarComic()" style="background-color:red;color:white">Eliminar</button>
    </div>
</template>

<script>
export default {
    name: "ComicComponent",
    props: ["comic", "index"],
    methods: {
        seleccionarFav() {
            this.$emit("seleccionarFav", this.comic);
        },
        eliminarComic() {
            this.$emit("eliminarComic", this.index);
        }
    }
}
</script>

<style>
@import "../assets//css/estilocomics.css";
</style>

// FRONT/ANGULAR/angularmodeloscomunicacion/src/app/components/comic/comic.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Comic } from 'src/app/models/Comic';

@Component({
  selector: 'app-comic',
  templateUrl: './comic.component.html',
  styleUrls: ['./comic.component.css'],
})
export class ComicComponent {
  @Input() comic!: Comic;
  @Output() modificarComicPadre = new EventEmitter();
  @Output() eliminarComicPadre = new EventEmitter();
  @Output() selectFavPadre = new EventEmitter();

  modificarComicHijo(event: any) {
    this.modificarComicPadre.emit(this.comic);
  }

  eliminarComicHijo(event: any) {
    this.eliminarComicPadre.emit(this.comic);
  }

  selectFavHijo(event: any) {
    this.selectFavPadre.emit(this.comic);
  }
}

<div>
  <h2>{{ comic.titulo }}</h2>
  <img [src]="comic.imagen" width="100" height="150" />
  <h3>{{ comic.descripcion }}</h3>
  <button
    (click)="modificarComicHijo($event)"
    style="color: white; background-color: blue"
  >
    Modificar cómic
  </button>
  <br />
  <button
    (click)="eliminarComicHijo($event)"
    style="color: white; background-color: red"
  >
    Eliminar cómic
  </button>
  <br />
  <button (click)="selectFavHijo($event)">Marcar como fav</button>
</div>
