// FRONT/VUE/vueauth/src/components/HomeComponent.vue
<template>
  <div>
    <h1>Página principal</h1>
    <hr class="border border-danger opacity-100" />
    <form v-if="empleados.length == 0" @submit.prevent="autenticacion()">
      <div class="mt-3">
        <label class="form-label">Usuario</label>
        <input type="text" class="form-control" v-model="username" />
      </div>
      <div class="mt-3">
        <label class="form-label">Contaseña</label>
        <input type="text" class="form-control" v-model="contraseña" />
      </div>
      <button class="btn btn-primary w-100 mt-3">Iniciar sesión</button>
    </form>
    <table class="table" v-else>
      <thead>
        <tr>
          <th>ID</th>
          <th>Apellido</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="emple in empleados" :key="emple">
          <td>{{ emple.idEmpleado }}</td>
          <td>{{ emple.apellido }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
import ServiceAuth from "../services/ServiceAuth";
const service = new ServiceAuth();

export default {
  name: "HomeComponent",
  data() {
    return {
      username: "",
      contraseña: "",
      token: "",
      empleados: [],
    };
  },
  methods: {
    autenticacion() {
      service.iniciarSesion(this.username, this.contraseña).then((result) => {
        this.token = result;
        service.getEmple().then((result) => {
          this.empleados = result;
        });
      });
    },
  },
};
</script>

// FRONT/ANGULAR/angularoauth/src/app/components/home/home.component.ts
import { Component, ElementRef } from '@angular/core';
import { ServiceOAuth } from 'src/app/services/service.oauth';
import { ViewChild } from '@angular/core';
import { Empleado } from 'src/app/models/Empleado';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent {
  public token!: string;
  public empleados!: Empleado[];

  @ViewChild('controluser') controlUser!: ElementRef;
  @ViewChild('controlpassword') controlPassword!: ElementRef;

  constructor(private _service: ServiceOAuth) {}

  autenticacion() {
    let userName: string = this.controlUser.nativeElement.value;
    let password: string = this.controlPassword.nativeElement.value;
    this._service.getAuthToken(userName, password).subscribe((response) => {
      this.token = response.response;
      this._service.getEmpleados(this.token).subscribe((response) => {
        this.empleados = response;
      });
    });
  }
}

<div>
  <h1>Página OAuth</h1>
  <hr class="border border-danger opacity-100" />
  <form #authform="ngForm" (ngSubmit)="autenticacion()" *ngIf="!empleados">
    <div class="mt-3">
      <label class="form-label">Usuario</label>
      <input type="text" class="form-control" name="controluser" #controluser />
    </div>
    <div class="mt-3">
      <label class="form-label">Contraseña</label>
      <input
        type="text"
        class="form-control"
        name="controlpassword"
        #controlpassword
      />
    </div>
    <button class="btn btn-primary w-100 mt-3">Enviar datos</button>
  </form>
  <table *ngIf="empleados" class="table">
    <thead class="border-danger">
      <tr>
        <th>ID</th>
        <th>Apellido</th>
        <th>Oficio</th>
        <th>Salario</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let emple of empleados">
        <td>{{ emple.idEmpleado }}</td>
        <td>{{ emple.apellido }}</td>
        <td>{{ emple.oficio }}</td>
        <td>{{ emple.salario }}</td>
      </tr>
    </tbody>
  </table>
</div>
