// FRONT/REACT/reactcrudcoches/src/components/CreateCoche.js
import React, { Component } from 'react'
import Global from '../Global';
import { NavLink, Navigate } from 'react-router-dom';
import axios from 'axios';

export default class CreateCoche extends Component {
    cajaId = React.createRef();
    cajaMarca = React.createRef()
    cajaModelo = React.createRef();
    cajaConductor = React.createRef();
    cajaImagen = React.createRef();

    state = {
        status: false
    }

    createCoche = (event) => {
        event.preventDefault();
        console.log(event.target.files[0]);
        let coche = {
            idCoche: parseInt(this.cajaId.current.value),
            marca: this.cajaMarca.current.value,
            modelo: this.cajaModelo.current.value,
            conductor: this.cajaConductor.current.value,
            imagen: this.cajaImagen.current.value
        }
        let url = Global.urlApiCoches;
        let request = "api/Coches/InsertCoche";
        axios.post(url + request, coche).then((response) => {
            this.setState({
                status: true
            });
        });
    }

    render() {
        if (this.state.status)
            return (<Navigate to="/" />);
        else {
            return (
                <div className='container-fluid mt-3'>
                    <h1>Crear coche</h1>
                    <hr className='border border-primary opacity-100' />
                    <form>
                        <div className='mt-3'>
                            <label className='form-label'>ID Coche</label>
                            <input
                                className='form-control'
                                ref={this.cajaId}
                                type="number" />
                        </div >
                        <div className='mt-3'>
                            <label className='form-label'>Marca</label>
                            <input
                                className='form-control'
                                ref={this.cajaMarca}
                                type="text" />
                        </div>
                        <div className='mt-3'>
                            <label className='form-label'>Modelo</label>
                            <input
                                className='form-control'
                                ref={this.cajaModelo}
                                type="text" />
                        </div>
                        <div className='mt-3'>
                            <label className='form-label'>Conductor</label>
                            <input
                                className='form-control'
                                ref={this.cajaConductor}
                                type="text" />
                        </div>
                        <div className='mt-3'>
                            <label className='form-label'>Imagen</label>
                            <input
                                className='form-control'
                                ref={this.cajaImagen}
                                type="file" />
                        </div>
                        <div className="row mt-3">
                            <div className="col-6">
                                <button
                                    className="btn btn-success w-100"
                                    onClick={this.createCoche}>Crear</button>
                            </div>
                            <div className="col-6">
                                <NavLink
                                    className="btn btn-secondary w-100"
                                    to="/">Cancelar</NavLink>
                            </div>
                        </div>
                    </form >
                </div >
            )
        }

    }
}

// FRONT/VUE/vuecrudcoches/src/components/CreateCoche.vue
<template>
  <div>
    <h1>Crear Coche</h1>
    <hr class="border border-primary opacity-100" />
    <form @submit.prevent="createCoche()" class="w-75 mx-auto">
      <div class="mt-3">
        <label class="form-label">ID (se asigna solo en la API)</label>
        <input
          type="number"
          class="form-control"
          v-model="coche.idCoche"
          disabled
        />
      </div>
      <div class="mt-3">
        <label class="form-label">Marca</label>
        <input type="text" class="form-control" v-model="coche.marca" />
      </div>
      <div class="mt-3">
        <label class="form-label">Modelo</label>
        <input type="text" class="form-control" v-model="coche.modelo" />
      </div>
      <div class="mt-3">
        <label class="form-label">Conductor</label>
        <input type="text" class="form-control" v-model="coche.conductor" />
      </div>
      <div class="mt-3">
        <label class="form-label">Imagen</label>
        <input type="text" class="form-control" v-model="coche.imagen" />
      </div>
      <button class="mt-3 w-100 btn btn-primary">Crear coche</button>
    </form>
  </div>
</template>

<script>
import ServiceCoches from "@/services/ServiceCoches";
const service = new ServiceCoches();

export default {
  name: "CreateCoche",
  data() {
    return {
      coche: {
        idCoche: 0,
        marca: "",
        modelo: "",
        conductor: "",
        imagen: "",
      },
    };
  },
  methods: {
    createCoche() {
      service.createCoche(this.coche).then((result) => {
        console.log(result);
        this.$router.push("/");
      });
    },
  },
};
</script>
