// FRONT/ANGULAR/angularcrudseries/src/app/components/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Serie } from 'src/app/models/Serie';
import { ServiceSeries } from 'src/app/services/service.series';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css'],
})
export class MenuComponent implements OnInit {
  public series!: Serie[];

  constructor(private _service: ServiceSeries) {}

  ngOnInit(): void {
    this._service.getSeries().subscribe((response) => {
      this.series = response;
    });
  }
}

<nav
  class="navbar navbar-expand-md bg-danger"
  data-bs-theme="dark"
  *ngIf="series"
>
  <div class="container-fluid">
    <a class="navbar-brand" [routerLink]="['/']">CRUD Series</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/create']"> Nuevo personaje </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/update']"
            >Modificar personajes</a
          >
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Series
          </a>
          <ul class="dropdown-menu">
            <li *ngFor="let serie of series">
              <a class="dropdown-item" [routerLink]="['/serie', serie.idSerie]">
                {{ serie.nombre }}
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

// FRONT/VUE/vuecrudcoches/src/components/MenuComponent.vue
<template>
  <nav class="navbar navbar-expand-md bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <router-link class="navbar-brand" to="/">CRUD Coches</router-link>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <router-link class="nav-link" to="/create">Crear coche</router-link>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: "MenuComponent",
};
</script>
