// FRONT/VUE/vuecomunicacioncomponents/src/components/HijoNumero.vue
<template>
    <div>
        <h1>Número Hijo: {{ numero }}</h1>
        <button @click="sumarNum()">Sumar {{ numero }}</button>
    </div>
</template>

<script>
export default {
    name: "HijoNumero",
    props: ["numero"],
    methods: {
        sumarNum() {
            this.$emit("sumarNumero", this.numero)
        }
    }
}
</script>

// FRONT/REACT/reactclases/src/components/HijoNumero.js
import { Component } from "react";

class HijoNumero extends Component {
    suma = () => {
        this.props.sumarNum(this.props.numero)
    }

    render() {
        return (
            <div>
                <h1 style={{ color: "blue" }}>Número hijo: {this.props.numero}</h1>
                <button onClick={() => this.suma()}>Sumar {this.props.numero}</button>
            </div>
        );
    }
}

export default HijoNumero;
