// FRONT/VUE/vuecomunicacioncomponents/src/components/PadreNumeros.vue
<template>
    <div>
        <h1>Números Padre</h1>
        <h2>La suma es {{ suma }}</h2>
        <button @click="generarNumero()">Nuevo número</button>
        <hr />
        <div v-for="num in numeros" :key="num">
            <HijoNumero :numero="num" @sumarNumero="sumarNumero" />
        </div>
    </div>
</template>

<script>
import HijoNumero from './HijoNumero.vue';

export default {
    name: "PadreNumeros",
    components: { HijoNumero },
    data() {
        return {
            suma: 0,
            numeros: []
        }
    },
    methods: {
        generarNumero() {
            this.numeros.push(parseInt(Math.random() * 100) + 1);
        },

        sumarNumero(numero) {
            this.suma += numero;
        }
    }
}
</script>

// FRONT/REACT/reactclases/src/components/PadreNumeros.js
import { Component } from "react";
import HijoNumero from "./HijoNumero";

class PadreNumeros extends Component {
    state = {
        suma: 0,
        numeros: [parseInt(Math.random() * 100 + 1)]
    }

    anyadirNum = () => {
        this.state.numeros.push(parseInt(Math.random() * 100 + 1));
        this.setState({
            numeros: this.state.numeros
        })
    }

    sumarNum = (num) => {
        this.setState({
            suma: this.state.suma + num
        })
    }

    render() {
        return (
            <div>
                <h1 style={{ color: "red" }}>La suma es {this.state.suma}</h1>
                <button onClick={() => this.anyadirNum()}>Nuevo número</button>
                {
                    this.state.numeros.map((num, index) => {
                        return (<HijoNumero numero={num} key={index} sumarNum={this.sumarNum} />)
                    })
                }
            </div>
        );
    }
}

export default PadreNumeros;
