// FRONT/REACT/reactcruddepartamentos/src/components/CreateDepartamento.js
import React, { Component } from 'react'
import Global from '../Global';
import axios from 'axios';
import { Navigate } from 'react-router-dom';

export default class CreateDepartamento extends Component {
    cajaNum = React.createRef();
    cajaNombre = React.createRef();
    cajaLocalidad = React.createRef();

    state = {
        status: false
    }

    insertDepartamento = (event) => {
        event.preventDefault();
        let departamento = {
            numero: parseInt(this.cajaNum.current.value),
            nombre: this.cajaNombre.current.value,
            localidad: this.cajaLocalidad.current.value
        }
        let url = Global.urlApiDept;
        let request = "api/Departamentos";
        axios.post(url + request, departamento).then((response) => {
            this.setState({
                status: true
            });
        });
    }

    render() {
        if (this.state.status)
            return (<Navigate to="/" />);
        else {
            return (
                <div className='container-fluid mt-3'>
                    <h1>Crear Departamento</h1>
                    <form onSubmit={this.insertDepartamento}
                        className="mt-3 d-block mx-auto w-50">
                        <div className='mb-3'>
                            <label className='form-label'>
                                Número Dept
                            </label>
                            <input ref={this.cajaNum}
                                className='form-control' type="number" />
                        </div>
                        <div className='mb-3'>
                            <label className='form-label'>
                                Nombre
                            </label>
                            <input ref={this.cajaNombre}
                                className='form-control' type="text" />
                        </div>
                        <div className='mb-3'>
                            <label className='form-label'>
                                Localidad
                            </label>
                            <input ref={this.cajaLocalidad}
                                className='form-control' type="text" />
                        </div>
                        <button className='btn btn-primary d-block mx-auto'>
                            Crear departamento
                        </button>
                    </form>
                </div>
            );
        }
    }
}

// FRONT/VUE/vuecruddepartamentos/src/components/CreateDepartamento.vue
<template>
  <div>
    <h1>Crear departamento</h1>
    <hr class="border border-primary opacity-100" />
    <form @submit.prevent="insertDepartamento()" class="w-75 mx-auto">
      <div class="mt-3">
        <label class="form-label">ID</label>
        <input
          type="number"
          class="form-control"
          v-model="departamento.idDepartamento"
        />
      </div>
      <div class="mt-3">
        <label class="form-label">Nombre</label>
        <input type="text" class="form-control" v-model="departamento.nombre" />
      </div>
      <div class="mt-3">
        <label class="form-label">Localidad</label>
        <input
          type="text"
          class="form-control"
          v-model="departamento.localidad"
        />
      </div>
      <button class="btn btn-primary mt-3 w-100">Crear</button>
    </form>
  </div>
</template>

<script>
import ServiceDept from "../services/ServiceDept";
const service = new ServiceDept();

export default {
  name: "CreateDepartamento",
  data() {
    return {
      departamento: {
        idDepartamento: 0,
        nombre: "",
        localidad: "",
      },
    };
  },
  methods: {
    insertDepartamento() {
      service.createDepartamento(this.departamento).then((result) => {
        console.log(result);
        this.$router.push("/");
      });
    },
  },
};
</script>
