// FRONT/REACT/reactcruddepartamentos/src/components/MenuDepartamentos.js
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'
import homeImage from "../assets/images/home.jpg"

export default class MenuDepartamentos extends Component {
    render() {
        return (
            <nav className="navbar navbar-expand-lg navbar-dark bg-primary">
                <div className="container-fluid">
                    <img src={homeImage}
                        alt="Logo"
                        width="35"
                        height="30"
                        className="d-inline-block align-text-top me-2" />
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div className="navbar-nav">
                            <NavLink className="nav-link"
                                to="/">Home</NavLink>
                            <NavLink className="nav-link"
                                to="/create">Create</NavLink>
                        </div>
                    </div>
                </div>
            </nav>
        );
    }
}

// FRONT/VUE/vuecruddepartamentos/src/components/MenuDepartamentos.vue
<template>
  <nav class="navbar navbar-expand-md bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <router-link class="navbar-brand" to="/">
        CRUD Departamentos
      </router-link>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <router-link class="nav-link" to="/create">
              Crear departamento
            </router-link>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: "MenuDepartamentos",
};
</script>
