// FRONT/ANGULAR/angularcruddepartamentos/src/app/components/updatedepartamento/updatedepartamento.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { Departamento } from 'src/app/models/Departamento';
import { ServiceDepartamentos } from 'src/app/services/service.departamentos';
import { Router } from '@angular/router';

@Component({
  selector: 'app-updatedepartamento',
  templateUrl: './updatedepartamento.component.html',
  styleUrls: ['./updatedepartamento.component.css'],
})
export class UpdatedepartamentoComponent implements OnInit {
  public departamento!: Departamento;

  @ViewChild('controlnombre') controlNombre: ElementRef = new ElementRef('');
  @ViewChild('controllocalidad') controlLoc: ElementRef = new ElementRef('');

  constructor(
    private _activeRoute: ActivatedRoute,
    private _service: ServiceDepartamentos,
    private _router: Router
  ) {}

  ngOnInit(): void {
    this._activeRoute.params.subscribe((params: Params) => {
      if (params['id']) {
        this.departamento = new Departamento(
          parseInt(params['id']),
          params['nombre'],
          params['localidad']
        );
      }
    });
  }

  updateDepartamento(): void {
    let dept = new Departamento(
      this.departamento.idDepartamento,
      this.controlNombre.nativeElement.value,
      this.controlLoc.nativeElement.value
    );
    this._service.updateDepartamento(dept).subscribe((response) => {
      this._router.navigate(['/']);
    });
  }
}

<div *ngIf="departamento">
  <h1>Modificar Departamento {{ departamento.idDepartamento }}</h1>
  <hr class="border border-danger opacity-100" />
  <form #updateform="ngForm" (ngSubmit)="updateDepartamento()">
    <div class="mt-3">
      <label class="form-label">ID Dept</label>
      <input
        type="number"
        class="form-control"
        name="controlid"
        #controlid
        disabled
        [value]="departamento.idDepartamento"
      />
    </div>
    <div class="mt-3">
      <label class="form-label">Nombre</label>
      <input
        type="text"
        class="form-control"
        name="controlnombre"
        #controlnombre
        [value]="departamento.nombre"
      />
    </div>
    <div class="mt-3">
      <label class="form-label">Localidad</label>
      <input
        type="text"
        class="form-control"
        name="controllocalidad"
        #controllocalidad
        [value]="departamento.localidad"
      />
    </div>
    <button class="btn btn-primary w-100 mt-3">Modificar departamento</button>
  </form>
</div>
<img
  *ngIf="!departamento"
  class="d-block mx-auto"
  src="../../../assets/images/loading.gif"
/>

// FRONT/VUE/vuecruddepartamentos/src/components/UpdateDepartamento.vue
<template>
  <div>
    <h1>Modificar Departamento {{ this.$route.params.id }}</h1>
    <hr class="border border-primary opacity-100" />
    <form
      @submit.prevent="updateDepartamento()"
      v-if="departamento"
      class="w-75 mx-auto"
    >
      <div class="mt-3">
        <label class="form-label">ID</label>
        <input
          type="text"
          class="form-control"
          v-model="departamento.idDepartamento"
          disabled
        />
      </div>
      <div class="mt-3">
        <label class="form-label">Nombre</label>
        <input type="text" class="form-control" v-model="departamento.nombre" />
      </div>
      <div class="mt-3">
        <label class="form-label">Localidad</label>
        <input
          type="text"
          class="form-control"
          v-model="departamento.localidad"
        />
      </div>
      <button class="btn btn-primary w-100 mt-3">Modificar</button>
    </form>
    <img v-else src="../assets/images/loading.gif" />
  </div>
</template>

<script>
import ServiceDept from "../services/ServiceDept";
const service = new ServiceDept();

export default {
  name: "UpdateDepartamento",
  watch: {
    "$route.params.id"(nextVal, oldVal) {
      if (nextVal != oldVal) this.findDepartamento();
    },
  },
  data() {
    return {
      departamento: null,
    };
  },
  methods: {
    findDepartamento() {
      let dept = this.$route.params.id;
      service.searchDepartamento(dept).then((result) => {
        this.departamento = result;
      });
    },
    updateDepartamento() {
      service.updateDepartamento(this.departamento).then((result) => {
        console.log(result);
        this.$router.push("/");
      });
    },
  },
  mounted() {
    this.findDepartamento();
  },
};
</script>
