// FRONT/VUE/vuecruddepartamentos/src/components/CreateDepartamento.vue
<template>
  <div>
    <h1>Crear departamento</h1>
    <hr class="border border-primary opacity-100" />
    <form @submit.prevent="insertDepartamento()" class="w-75 mx-auto">
      <div class="mt-3">
        <label class="form-label">ID</label>
        <input
          type="number"
          class="form-control"
          v-model="departamento.idDepartamento"
        />
      </div>
      <div class="mt-3">
        <label class="form-label">Nombre</label>
        <input type="text" class="form-control" v-model="departamento.nombre" />
      </div>
      <div class="mt-3">
        <label class="form-label">Localidad</label>
        <input
          type="text"
          class="form-control"
          v-model="departamento.localidad"
        />
      </div>
      <button class="btn btn-primary mt-3 w-100">Crear</button>
    </form>
  </div>
</template>

<script>
import ServiceDept from "../services/ServiceDept";
const service = new ServiceDept();

export default {
  name: "CreateDepartamento",
  data() {
    return {
      departamento: {
        idDepartamento: 0,
        nombre: "",
        localidad: "",
      },
    };
  },
  methods: {
    insertDepartamento() {
      service.createDepartamento(this.departamento).then((result) => {
        console.log(result);
        this.$router.push("/");
      });
    },
  },
};
</script>

// FRONT/ANGULAR/angularcruddepartamentos/src/app/components/createdepartamento/createdepartamento.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { Departamento } from 'src/app/models/Departamento';
import { ServiceDepartamentos } from 'src/app/services/service.departamentos';

import { Router } from '@angular/router';

@Component({
  selector: 'app-createdepartamento',
  templateUrl: './createdepartamento.component.html',
  styleUrls: ['./createdepartamento.component.css'],
})
export class CreatedepartamentoComponent {
  @ViewChild('controlid') controlId: ElementRef = new ElementRef(0);
  @ViewChild('controlnombre') controlNombre: ElementRef = new ElementRef('');
  @ViewChild('controllocalidad') controlLoc: ElementRef = new ElementRef('');

  constructor(
    private _service: ServiceDepartamentos,
    private _router: Router
  ) {}

  createDepartamento(): void {
    let dept: Departamento = new Departamento(
      parseInt(this.controlId.nativeElement.value),
      this.controlNombre.nativeElement.value,
      this.controlLoc.nativeElement.value
    );
    this._service.createDepartamento(dept).subscribe((response) => {
      console.log(response);
      this._router.navigate(['/']);
    });
  }
}

<div>
  <h1>Crear departamento</h1>
  <hr class="border border-danger opacity-100" />
  <form #createform="ngForm" (ngSubmit)="createDepartamento()">
    <div class="mt-3">
      <label class="form-label">ID Dept</label>
      <input type="number" class="form-control" name="controlid" #controlid />
    </div>
    <div class="mt-3">
      <label class="form-label">Nombre</label>
      <input
        type="text"
        class="form-control"
        name="controlnombre"
        #controlnombre
      />
    </div>
    <div class="mt-3">
      <label class="form-label">Localidad</label>
      <input
        type="text"
        class="form-control"
        name="controllocalidad"
        #controllocalidad
      />
    </div>
    <button class="btn btn-primary w-100 mt-3">Crear departamento</button>
  </form>
</div>
